name: to_let_app_abandon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  shared_preferences: ^2.3.5
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  share_plus: ^10.1.4
  in_app_review: ^2.0.12
  pin_code_fields: ^9.4.0
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  flutter_local_notifications: ^22.3.0
  http: ^1.6.0
  supabase_flutter: ^2.8.0
  google_sign_in: ^6.2.1
  local_auth: ^3.0.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  flutter_dotenv: ^5.2.1
  logger: ^2.8.0
  device_info_plus: ^12.4.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/

# App launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"